---
title: "bayesian exercises"
output: html_document
date: "2025-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(144)
```

## R Markdown

```{r}
library(ggplot2)
x <- seq(-5, 10, by = .1)

y <- 0.5*dnorm(x, mean = 1, sd = 2) + 0.5*dnorm(x,2,2)


plot(x,y)
```

```{r}
dat <- read.table(text = "info mean sd
info1 1 2
info2 2 2
info3 1.5 2
", header = TRUE)

densities <- apply(dat[, -1], 1, function(x) rnorm(n = 2000, mean = x[1], sd = x[2]))
colnames(densities) <- dat$info

plot(0, type = "n", xlim = c(min(densities), max(densities)), ylim = c(0, .2))
for (d in 1:ncol(densities)){
  lines(density(densities[, d]), lty = d)
}
legend("topright", legend=colnames(densities), lty=1:ncol(densities))
```
```{r}
x <- 1

y1 <- dnorm(x, mean = 1, sd = 2)
y2 <- dnorm(x,2,2)

n <- y1/(y1+y2)
n
```

```{r}
library(dplyr)
library(GLMsData)
# Load data
data(ants)

# Set column names to lower case
ants_df <- ants %>%
  rename(sp_rich = Srich) %>%
  rename_with(tolower)

# What does the data look like?
glimpse(ants_df)
```
```{r}
library(brms)
summary(ants_df)
ants_df %>%
  ggplot(aes(x = sp_rich)) +
    geom_bar() +
    scale_x_continuous(limits = c(0, NA)) +
    facet_wrap(~habitat)
```

```{r}
ants_df %>%
  ggplot(aes(y = sp_rich, x = habitat)) +
    geom_boxplot() +
    geom_line(aes(colour = site, group = site), alpha = 0.5) +
    geom_point(aes(colour = site, group = site)) +
    scale_y_continuous(limits = c(0, NA))
```

```{r}
# Scatter plot of the number of species, related to the latitude per habitat
ants_df %>%
  ggplot(aes(y = sp_rich, x = latitude)) +
    geom_point() +
    geom_smooth(method = "loess", formula = "y ~ x", colour = "firebrick",
                level = 0.9) +
    facet_wrap(~habitat)

ants_df %>%
  ggplot(aes(y = sp_rich, x = elevation)) +
    geom_point() +
    geom_smooth(method = "loess", formula = "y ~ x", colour = "firebrick",
                level = 0.9) +
    facet_wrap(~habitat)
```

```{r}
library(rstan)
example(stan_model, run.dontrun = TRUE)

```


```{r}
library(brms)
nchains <- 3 # number of chains
niter <- 2000 # number of iterations (incl. warmup, see next)
warmup <- niter / 4 # number of initial samples to remove (= warmup)
nparallel <- nchains # number of cores for parallel computing
thinning <- 1 # thinning factor (here 1 = no thinning)


# Fit Normal model
fit_normal1 <- brm(
  formula = sp_rich ~ habitat, # specify the model
  family = gaussian(),         # we use the Normal distribution
  data = ants_df,              # specify data
  chains = nchains,            # MCMC parameters
  warmup = warmup, 
  iter = niter,
  cores = nparallel,
  thin = thinning,
  seed = 123)                  # seed for reproducibility
```

```{r}
library(ggplot2)
library(dplyr)
install.packages("bayesplot")
install.packages("tidyr")
library(bayesplot)
library(tidyr)
fit_normal1
color_scheme_set("mix-blue-red")
parameters <- c("b_Intercept", "b_habitatForest", "sigma")
# Visualisation by extracting samples with as_draws_df()
as_draws_df(fit_normal1, variable = parameters) %>%
  # long format
  pivot_longer(cols = all_of(parameters), names_to = "parameter",
               values_to = "value") %>%
  # visualise with ggplot()
  ggplot(aes(y = value, x = .iteration, colour = factor(.chain))) +
    geom_line() +
    facet_wrap(~parameter, nrow = 3, scales = "free")
```

```{r}
mcmc_trace(fit_normal1, pars = parameters)
```

```{r}
library(tidyr)
cumquant <- function(x, p) {
  out <- sapply(seq_along(x),
                function(k, z) quantile(z[1:k], probs = p[1], names = FALSE),
                z = x)
  return(out)
}

as_draws_df(fit_normal1, variable = parameters) %>%
  mutate(across(all_of(parameters), ~cummean(.x),
                .names = "{.col}_mean"),
         across(all_of(parameters), ~cumquant(.x, 0.05),
                .names = "{.col}_q05"),
         across(all_of(parameters), ~cumquant(.x, 0.95),
                .names = "{.col}_q95")) %>%
  select(-all_of(parameters)) %>%
  # long format for visualisation
  pivot_longer(cols = starts_with(parameters), names_to = "name",
               values_to = "value") %>%
  # split columns names at the last underscore
  tidyr::extract(name, into = c("parameter", "statistic"), "(.*)_([^_]+)$") %>%
  ggplot(aes(y = value, x = .iteration, colour = factor(.chain))) +
    geom_line(aes(linetype = statistic), linewidth = 0.8) +
    facet_wrap(~parameter, nrow = 3, scales = "free")
```
```{r}
mcmc_dens_overlay(fit_normal1, pars = parameters)
```

```{r}
pp_check(fit_normal1, type = "dens_overlay_grouped", ndraws = 100, 
         group = "habitat")
```

```{r}
fit_poisson1 <- brm(
  formula = sp_rich ~ habitat, # specify the model
  family = poisson(),          # we use the Poisson distribution
  data = ants_df,              # specify the data
  chains = nchains,            # MCMC parameters
  warmup = warmup, 
  iter = niter,
  cores = nparallel,
  thin = thinning,
  seed = 123)                  # seed for reproducibility
```

```{r}
plot(fit_poisson1)
```
```{r}
parameters <- c("b_Intercept", "b_habitatForest")
mcmc_dens_overlay(fit_poisson1, pars = parameters)
```

```{r}
library("rstan")
conflicted::conflicts_prefer(rstan::extract)
conflicted::conflicts_prefer(brms::loo)

stan_poisson_model_code = '
data {
  int<lower=1> N;                   // sample size
  vector[N] habitat_obs;            // habitat
  array[N] int<lower=0> sp_rich;    // outcome variable: number of ants
}

parameters {
  real intercept_rich;              // intercept
  real habitat_effect;              // slope
}

model {
  // priors
  intercept_rich ~ normal(0, 1);
  habitat_effect ~ normal(0, 1);

  // "posterior", "likelihood", ... give it a name!
  sp_rich ~ poisson_log(intercept_rich + habitat_effect * habitat_obs);

}

'

stan_poisson_model <- stan_model(
  # file = here("code", "brms_modeling", "poisson_model.stan"),
  model_code = stan_poisson_model_code, 
  model_name = "stan poisson model"
  )
```


```{r}
stan_poisson_fit <- sampling(
  stan_poisson_model,
  list(
    N = nrow(ants_df),
    habitat_obs = as.integer(ants_df$habitat)-1,
    sp_rich = ants_df$sp_rich
    ),
  iter = niter,
  chains = nchains,
  cores = nparallel
  )

stan_poisson_fit


library("shinystan")
launch_shinystan(stan_poisson_fit)
```





```{r}
library(tidyverse)
library(brms)
library(tidybayes)
library(lme4)
library(lattice)

# get data
data(sleepstudy, package = "lme4")

# fit example model
prior1 <- prior(normal(0, 3), class = b)

fit_mcmc <- brm(Reaction ~ Days + (1 | Subject),
                data = sleepstudy, prior = prior1,
                cores = 2,
                sample_prior = "yes")

fit_reml <- lmer(Reaction ~ Days + (1 | Subject),
                 data = sleepstudy)

# extract prior and posterior samples for Days
prior_draws <- tibble(b_Days = prior_draws(fit_mcmc, variable = "b")$b)
post_draws <- as_tibble(as_draws_df(fit_mcmc))

draws <- bind_rows(prior = prior_draws, posterior = post_draws, .id = "dist")

# extract parameter density
prof <- densityplot(profile(fit_reml, "Days"), bw = "SJ", kernel = "gaussian")
lik <- tibble(b_Days = seq(prof$x.limits[[1]][1], prof$x.limits[[1]][2], length.out = 201),
              density = prof$call$data$density,
              dist = "likelihood")

# plot
ggplot(draws, aes(x = b_Days, fill = dist))+
  stat_slab(alpha = 0.5)+
  geom_ribbon(data = lik, aes(ymax = density), ymin = 0, color = "transparent", alpha = 0.5)+
  scale_fill_manual(name = "", values = c("#4477AA", "#228833", "#CCBB44"))+
  theme_linedraw()
```

```{r}
# fit example model
prior1 <- prior(normal(-10, 3), class = b)

fit_mcmc <- brm(Reaction ~ Days + (1 | Subject),
                data = sleepstudy, prior = prior1,
                cores = 2,
                sample_prior = "yes")

fit_reml <- lmer(Reaction ~ Days + (1 | Subject),
                 data = sleepstudy)

# extract prior and posterior samples for Days
prior_draws <- tibble(b_Days = prior_draws(fit_mcmc, variable = "b")$b)
post_draws <- as_tibble(as_draws_df(fit_mcmc))

draws <- bind_rows(prior = prior_draws, posterior = post_draws, .id = "dist")

# extract parameter density
prof <- densityplot(profile(fit_reml, "Days"), bw = "SJ", kernel = "gaussian")
lik <- tibble(b_Days = seq(prof$x.limits[[1]][1], prof$x.limits[[1]][2], length.out = 201),
              density = prof$call$data$density,
              dist = "likelihood")

# plot
ggplot(draws, aes(x = b_Days, fill = dist))+
  stat_slab(alpha = 0.5)+
  geom_ribbon(data = lik, aes(ymax = density), ymin = 0, color = "transparent", alpha = 0.5)+
  scale_fill_manual(name = "", values = c("#4477AA", "#228833", "#CCBB44"))+
  theme_linedraw()

summary(fit_mcmc)

```
```{r}

# fit example model
prior1 <- prior(normal(-10, 30), class = b)

fit_mcmc <- brm(Reaction ~ Days + (1 | Subject),
                data = sleepstudy, prior = prior1,
                cores = 2,
                sample_prior = "yes")

fit_reml <- lmer(Reaction ~ Days + (1 | Subject),
                 data = sleepstudy)

# extract prior and posterior samples for Days
prior_draws <- tibble(b_Days = prior_draws(fit_mcmc, variable = "b")$b)
post_draws <- as_tibble(as_draws_df(fit_mcmc))

draws <- bind_rows(prior = prior_draws, posterior = post_draws, .id = "dist")

# extract parameter density
prof <- densityplot(profile(fit_reml, "Days"), bw = "SJ", kernel = "gaussian")
lik <- tibble(b_Days = seq(prof$x.limits[[1]][1], prof$x.limits[[1]][2], length.out = 201),
              density = prof$call$data$density,
              dist = "likelihood")

# plot
ggplot(draws, aes(x = b_Days, fill = dist))+
  stat_slab(alpha = 0.5)+
  geom_ribbon(data = lik, aes(ymax = density), ymin = 0, color = "transparent", alpha = 0.5)+
  scale_fill_manual(name = "", values = c("#4477AA", "#228833", "#CCBB44"))+
  theme_linedraw()
```


```{r}
# fit example model
prior_c <- prior(cauchy(-10, 2.39))

fit_mcmc <- brm(Reaction ~ Days + (1 | Subject),
                data = sleepstudy, prior = prior_c,
                cores = 2,
                sample_prior = "yes")

fit_reml <- lmer(Reaction ~ Days + (1 | Subject),
                 data = sleepstudy)

# extract prior and posterior samples for Days
prior_draws <- tibble(b_Days = prior_draws(fit_mcmc, variable = "b")$b)
post_draws <- as_tibble(as_draws_df(fit_mcmc))

draws <- bind_rows(prior = prior_draws, posterior = post_draws, .id = "dist")

# extract parameter density
prof <- densityplot(profile(fit_reml, "Days"), bw = "SJ", kernel = "gaussian")
lik <- tibble(b_Days = seq(prof$x.limits[[1]][1], prof$x.limits[[1]][2], length.out = 201),
              density = prof$call$data$density,
              dist = "likelihood")

# plot
ggplot(draws, aes(x = b_Days, fill = dist))+
  stat_slab(alpha = 0.5)+
  geom_ribbon(data = lik, aes(ymax = density), ymin = 0, color = "transparent", alpha = 0.5)+
  scale_fill_manual(name = "", values = c("#4477AA", "#228833", "#CCBB44"))+
  theme_linedraw()
summary(fit_mcmc)

```

```{r}
library(ggplot2)
tibble(x = seq(-30, 10, length.out = 400)) |>
  mutate(
    normal = dnorm(x, -10, 3),
    cauchy = dcauchy(x, -10, 3)
  ) |>
  pivot_longer(-x, names_to = "dist", values_to = "density") |>
  ggplot(aes(x, density, color = dist)) +
  geom_line(linewidth = 1) +
  theme_minimal()

```
```{r}
# analytic center densities
norm_peak <- dnorm(-10, mean = -10, sd = 3)   # normal location -10, sd 3
cauchy_peak <- dcauchy(-10, location = -10, scale = 3) # cauchy location -10, scale 3
norm_peak; cauchy_peak


```

```{r}
sc<- c(-7,-5,-3,-3,1,6,7,13,15,16,20,21)
ps<-c(8,8,8,8,8,8,8,8,8,8,8,8)
diff<- sc-ps
diff
mean(diff)
sd(diff)
var(diff)
```

```{r}
p1<-1-pnorm(-8, mean(diff),sd(diff))
p2<-1-pnorm(0, mean(diff),sd(diff))
p3<-p2/p1
p1
p2
p3
```



```{r}
mydata <- data.frame(x = diff)
ggplot(mydata, aes(x)) +
  geom_histogram(aes(y = ..density..), binwidth = 0.5,
                 fill = "cornsilk", color = "black") +
  stat_function(fun = dnorm, args = list(mean = mean(diff), sd = sd(diff)), color = "maroon")
```


```{r}
# Creating the Sequence
gfg = seq(0,1, by=0.01)

# Case 3
plot(gfg, dbeta(gfg, 4,4), xlab = "X",
     ylab = "Beta Density", type = "l",
     col = "Red") 
```
```{r}
# robust stuff
set.seed(123)

n <- 3
theta_true <- 2
sigma_true <- 1
y <- rnorm(n, mean = theta_true, sd = sigma_true)

data <- data.frame(y = y)

library(brms)

base_prior <- prior(normal(0, 2), class = "Intercept")

fit_base <- brm(
  y ~ 1,
  data = data,
  prior = base_prior,
  family = gaussian(),
  seed = 123,
  iter = 2000,
  chains = 4
)

```

```{r}
priors_list <- list(
  prior(normal(0, 2), class = "Intercept"),  # base
  prior(normal(0, 5), class = "Intercept"),  # more diffuse
  prior(normal(2, 2), class = "Intercept"),  # shifted mean
  prior(normal(-2, 2), class = "Intercept"), # shifted the other way
  prior(student_t(3, 0, 2), class = "Intercept") # heavy-tailed prior
)

```

```{r}
fits <- lapply(priors_list, function(pr) {
  brm(y ~ 1, data = data, prior = pr,
      family = gaussian(), seed = 123, iter = 2000, chains = 4,
      refresh = 0)
})

library(dplyr)

posterior_summary <- function(fit) {
  s <- as.data.frame(summary(fit)$fixed)
  # Try different possible column names
  ci_lower <- intersect(c("l-95% CI", "Q2.5"), names(s))
  ci_upper <- intersect(c("u-95% CI", "Q97.5"), names(s))
  
  # Pick the first matching names
  s_out <- s[, c("Estimate", ci_lower[1], ci_upper[1])]
  names(s_out) <- c("Estimate", "Lower", "Upper")
  s_out
}

results <- lapply(fits, posterior_summary)
names(results) <- c("Normal(0,2)", "Normal(0,5)", "Normal(2,2)",
                    "Normal(-2,2)", "StudentT(3,0,2)")

bind_rows(results, .id = "Prior")
```

```{r}
library(bayesplot)

posterior_draws <- lapply(fits, as_draws_df)
names(posterior_draws) <- names(results)

```
```{r}
library(ggplot2)
library(dplyr)

# Define a grid of theta values
theta <- seq(-8, 8, length.out = 400)

priors_df <- tibble(
  theta = theta,
  `Normal(0,2)`   = dnorm(theta, 0, 2),
  `Normal(0,5)`   = dnorm(theta, 0, 5),
  `Normal(2,2)`   = dnorm(theta, 2, 2),
  `Normal(-2,2)`  = dnorm(theta, -2, 2),
  `StudentT(3,0,2)` = dt((theta - 0)/2, df = 3) / 2  # scaled t
) |>
  tidyr::pivot_longer(-theta, names_to = "Prior", values_to = "Density")

ggplot(priors_df, aes(x = theta, y = Density, color = Prior)) +
  geom_line(size = 1.2) +
  theme_minimal(base_size = 14) +
  labs(title = "Prior Distributions for θ",
       x = expression(theta), y = "Density") +
  scale_color_brewer(palette = "Dark2")

```

```{r}
library(posterior)

posterior_draws <- lapply(fits, as_draws_df)
names(posterior_draws) <- names(priors_list)
names(posterior_draws) <- c("Normal(0,2)", "Normal(0,5)", "Normal(2,2)",
                            "Normal(-2,2)", "StudentT(3,0,2)")

```

```{r}
library(tibble)
library(dplyr)

library(tibble)
library(dplyr)

post_df <- bind_rows(
  lapply(names(posterior_draws), function(nm) {
    df <- posterior_draws[[nm]]
    tibble(theta = df$b_Intercept, Prior = nm)
  })
)


ggplot(post_df, aes(x = theta,  color = Prior)) +
  geom_density(alpha = 0.3, size = 1) +
  theme_minimal(base_size = 14) +
  labs(title = "Posterior Distributions under Different Priors",
       x = expression(theta),
       y = "Density")

```

```{r}
theta_grid <- seq(-5, 5, length.out = 400)

priors_df <- tibble(
  theta = theta_grid,
  `Normal(0,2)`   = dnorm(theta_grid, 0, 2),
  `Normal(0,5)`   = dnorm(theta_grid, 0, 5),
  `Normal(2,2)`   = dnorm(theta_grid, 2, 2),
  `Normal(-2,2)`  = dnorm(theta_grid, -2, 2),
  `StudentT(3,0,2)` = dt((theta_grid - 0)/2, df = 3) / 2
) |>
  tidyr::pivot_longer(-theta, names_to = "Prior", values_to = "Density")

ggplot() +
 
  stat_function(fun = dnorm, n = 101, args = list(mean = 2, sd = 1)) + ylab("") +
  scale_y_continuous(breaks = NULL)+
  geom_line(data = priors_df, aes(x = theta, y = Density, color = Prior),
            linewidth = 0.7, linetype = "dashed") +
  geom_density(data = post_df, aes(x = theta,  color = Prior),
               alpha = 0.3, linewidth = .7) +
  theme_minimal(base_size = 14) +
  labs(title = "Prior (dashed) vs Posterior (solid) Distributions",
       x = expression(theta), y = "Density") 

```

```{r}
# e-contamination

prior = mixture((1-e)*normal(0,2), e*normal(5,2), order = 'mu')

prior <- c(prior(normal(-2.5,.1), Intercept, dpar = mu1),
            prior(normal(7,.1), Intercept, dpar = mu2),
            prior(normal(-8,1), alpha2))

model <- brm(bf(formula = accuracy  ~ 1, 
                    theta1 = 1, theta2 = 3),
                    data = dat,
                    family = mix,
                    warmup = 1000, iter = 5000, 
                    cores = parallel::detectCores(),
                    chains = 4, control = list(adapt_delta = .97), 
                    prior = prior,
                    inits = 0,
                    save_pars = save_pars(all = TRUE))
```


```{r}
# prior predictive incorrect
library(MASS)
library(ggplot2)

# squared exponential kernel
k_se <- function(x1, x2, ell, sigma2) {
  outer(x1, x2, function(a, b)
    sigma2 * exp(-(a - b)^2 / (2 * ell^2))
  )
}

x <- seq(0, 10, length.out = 200)

simulate_gp <- function(ell, sigma2) {
  K <- k_se(x, x, ell, sigma2)
  L <- chol(K + 1e-6 * diag(length(x)))
  drop(t(L) %*% rnorm(length(x)))
}

#! change this
# param grid
ells    <- c(0.3, 1.0)
vars    <- c(0.5, 2.0)

results <- list()

for (ell in ells) {
  for (v in vars) {
    f <- simulate_gp(ell, v)
    results[[paste(ell, v, sep="_")]] <-
      data.frame(x = x, f = f, ell = ell, var = v)
  }
}

df <- do.call(rbind, results)

ggplot(df, aes(x, f)) +
  geom_line() +
  facet_grid(ell ~ var, labeller = label_both) +
  theme_minimal() +
  labs(title = "Gaussian Process Prior Samples (Squared Exponential Kernel)",
       y = "f(x)")

```
```{r}
library(ggplot2)
# prior predictive redo

set.seed(144)
# squared exponential kernel
k_se <- function(x1, x2, lambda, sigma) {
  outer(x1, x2, function(a, b)
    (sigma^2) * exp(-(a - b)^2 / (2 * lambda^2))
  )
}

grid_x <- seq(0, 10, length.out = 200)

simulate_gp <- function(lambda, sigma, x) {
  K <- k_se(x, x, lambda, sigma)
  L <- chol(K + 1e-6 * diag(length(x)))
  drop(t(L) %*% rnorm(length(x)))
}

# hyperparameter grids
ig_alpha <- c(1, 2, 3)
ig_beta  <- c(1, 2, 3)

ht_mu   <- 0
ht_df   <- c(3, 5, 7)
ht_scale <- c(0.5, 1.0)

results <- list()


idx <- 1
for (a in ig_alpha) {
  for (b in ig_beta) {
    for (df_ in ht_df) {
      for (s in ht_scale) {

        lambda_draw   <- 1 / rgamma(1, shape = a, rate = b) # inv-gamma
        sigma_draw <- ht_mu + s * varhalfT(runif(1), n = df_)#abs(rt(1, df = df_) * s) # half-t

        f <- simulate_gp(lambda_draw, sigma_draw, grid_x)

        results[[idx]] <-
          data.frame(x = grid_x,
                     f = f,
                     lambda = lambda_draw,
                     sigma = sigma_draw,
                     alpha = a,
                     beta = b,
                     df = df_,
                     scale = s)
        idx <- idx + 1
      }
    }
  }
}


df <- do.call(rbind, results)

ggplot(df, aes(x, f)) +
  geom_line(alpha = 0.7) +
  facet_grid(alpha + beta ~ df + scale, labeller = label_both) +
  theme_minimal() +
  labs(title = "Gaussian Process Prior Samples (Squared Exponential Kernel)",
       y = "f(x)")

```


```{r}
# half-t 
library(VaRES)

# parameters for half-t
mu <- 5
df  <- 1
scale <- 2

# grid
x <- seq(0, 10, length.out = 500)

d_halfT_scaled <- function(x, df, mu, scale) {
  z <- (x - mu) / scale
  z[z < 0] <- NA                 
  dhalfT(z, n = df) / scale
}

?dhalfT

y <- d_halfT_scaled(x, df, mu, scale)

plot(x, y, type = "l", lwd = 2,
     main = paste0("Half-t Distribution (df = ", df, ", mu = ", mu,  ", scale = ", scale, ")"),
     xlab = "x", ylab = "density")

```
```{r} 
# inverse-gaussian
library(statmod)

# parameters for inv-gaussian
mean <- 3
shape  <- 1

# grid
x <- seq(0, 10, length.out = 500)

y <- dinvgauss(x, mean=mean, shape=shape)

plot(x, y, type = "l", lwd = 2,
     main = paste0("Inv-Gaussian (mean = ", mean, ", shape = ", shape, ")"),
     xlab = "x", ylab = "density")


```


```{r}

```

