---
title: "lgpr textbook analysis from https://jtimonen.github.io/lgpr-usage/tutorials/basic.html#6_Visualizing_the_inferred_covariate_effects"
output: html_document
date: "2026-02-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require("lgpr")
require("rstan")
require("ggplot2")
```

```{r}
plot_data(testdata_002, facet_by = "id", color_by = "sex") + xlab("Age (months)")
```
```{r}
plot_data(testdata_002, facet_by = "id", color_by = "diseaseAge") + scale_color_gradient2() + xlab("Age (months)")
```
```{r}
model <- create_model(
  y ~ gp(age) + zs(id) * gp(age) + zs(sex) * gp(age) + gp_vm(diseaseAge) + zs(group),
  testdata_002
)
print(model)
```

```{r}
prior <- list(
  alpha = lgpr::normal(mu = 0, sigma = 1), # gaussian for magnitudes <alpha>
  ell = lgpr::igam(shape = 5, scale = 5) # inverse gamma for lengthscales <ell>
)

model <- create_model(y ~ age + age | sex + age | id,
  data = testdata_002,
  prior = prior
)
param_summary(model)
```

```{r}
num_draws <- 300
mu_wrp <- -0.7
sigma_wrp <- 0.3
r <- range(testdata_002$diseaseAge, na.rm = TRUE)

# Define prior for lgp()
my_prior <- list(wrp = log_normal(mu_wrp, sigma_wrp))

# Prior draws
wrp_draws <- stats::rlnorm(num_draws, mu_wrp, sigma_wrp)

# Plot corresponding input warping functions
# - this function is not exported from lgpr so we need to use triple colons :::
# - alpha here is line opacity, not a GP parameter
lgpr:::plot_inputwarp(wrp_draws, seq(r[1], r[2], by = 1), alpha = 0.1)
```
```{r}
fit <- lgp(y ~ gp(age) + zs(id) * gp(age) + zs(sex) * gp(age) + gp_vm(diseaseAge) + zs(group),
  data     = testdata_002,
  prior    = my_prior, # defined earlier
  iter     = 2000,
  chains   = 4,
  refresh  = 500,
  cores = 4
)
```
```{r}
print(fit)
```

```{r}
plot_draws(fit, type = "dens")
```
```{r}
sf <- fit@stan_fit
sampler_params <- rstan::get_sampler_params(sf, inc_warmup = FALSE)
myfun <- function(x) mean(x[, "accept_stat__"])
mean_accept_stat_by_chain <- sapply(sampler_params, myfun)
print(mean_accept_stat_by_chain)
```
```{r}
Relevance <- relevances(fit)
data.frame(Relevance)
```
```{r}
select(fit, threshold = 0.95)
```
```{r}
threshold_density <- function(x) {
  stats::dbeta(x, 20, 2)
}
s <- select.integrate(fit, p = threshold_density)

print(s$expected)
```
```{r}
t <- seq(1, 120, by = 1)
x_pred <- new_x(testdata_002, t, x_ns = "diseaseAge")
p <- pred(fit, x_pred) # use posterior mean kernel parameters
# Computing analytic function posteriors... 
# Done.
plot_pred(fit, pred = p)
```
```{r}
plot_components(fit,
  pred = p,
  color_by = c(NA, NA, "sex", "group", "group", "group"),
  ylim = c(-3, 2),
  ncol = 2
)
```
```{r}
plot_pred(fit)
```
```{r}
plot_components(fit,
  color_by = c(NA, NA, "sex", "group", "group", "group"),
  ylim = c(-3, 2),
  ncol = 2
)
```


